// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: Configger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/config.go -package=test -mock_names=Configger=MockConfig . Configger
//

// Package test is a generated GoMock package.
package test

import (
	config "github/M2A96/Monopoly.git/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Configger interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
	isgomock struct{}
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetDatabaseConfigger mocks base method.
func (m *MockConfig) GetDatabaseConfigger() config.DatabaseConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseConfigger")
	ret0, _ := ret[0].(config.DatabaseConfigger)
	return ret0
}

// GetDatabaseConfigger indicates an expected call of GetDatabaseConfigger.
func (mr *MockConfigMockRecorder) GetDatabaseConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseConfigger", reflect.TypeOf((*MockConfig)(nil).GetDatabaseConfigger))
}

// GetHTTPConfigger mocks base method.
func (m *MockConfig) GetHTTPConfigger() config.HTTPConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHTTPConfigger")
	ret0, _ := ret[0].(config.HTTPConfigger)
	return ret0
}

// GetHTTPConfigger indicates an expected call of GetHTTPConfigger.
func (mr *MockConfigMockRecorder) GetHTTPConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHTTPConfigger", reflect.TypeOf((*MockConfig)(nil).GetHTTPConfigger))
}

// GetLogConfigger mocks base method.
func (m *MockConfig) GetLogConfigger() config.LogConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogConfigger")
	ret0, _ := ret[0].(config.LogConfigger)
	return ret0
}

// GetLogConfigger indicates an expected call of GetLogConfigger.
func (mr *MockConfigMockRecorder) GetLogConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogConfigger", reflect.TypeOf((*MockConfig)(nil).GetLogConfigger))
}

// GetOtelConfigger mocks base method.
func (m *MockConfig) GetOtelConfigger() config.OtelConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOtelConfigger")
	ret0, _ := ret[0].(config.OtelConfigger)
	return ret0
}

// GetOtelConfigger indicates an expected call of GetOtelConfigger.
func (mr *MockConfigMockRecorder) GetOtelConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOtelConfigger", reflect.TypeOf((*MockConfig)(nil).GetOtelConfigger))
}

// GetRuntimeConfigger mocks base method.
func (m *MockConfig) GetRuntimeConfigger() config.RuntimeConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeConfigger")
	ret0, _ := ret[0].(config.RuntimeConfigger)
	return ret0
}

// GetRuntimeConfigger indicates an expected call of GetRuntimeConfigger.
func (mr *MockConfigMockRecorder) GetRuntimeConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeConfigger", reflect.TypeOf((*MockConfig)(nil).GetRuntimeConfigger))
}

// GetServerConfigger mocks base method.
func (m *MockConfig) GetServerConfigger() config.ServerConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerConfigger")
	ret0, _ := ret[0].(config.ServerConfigger)
	return ret0
}

// GetServerConfigger indicates an expected call of GetServerConfigger.
func (mr *MockConfigMockRecorder) GetServerConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerConfigger", reflect.TypeOf((*MockConfig)(nil).GetServerConfigger))
}
