// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/object/dao (interfaces: Cursorer)
//
// Generated by this command:
//
//	mockgen -destination=../../test/v2/cursor.go -package=test -mock_names=Cursorer=MockCursor . Cursorer
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockCursor is a mock of Cursorer interface.
type MockCursor struct {
	ctrl     *gomock.Controller
	recorder *MockCursorMockRecorder
	isgomock struct{}
}

// MockCursorMockRecorder is the mock recorder for MockCursor.
type MockCursorMockRecorder struct {
	mock *MockCursor
}

// NewMockCursor creates a new mock instance.
func NewMockCursor(ctrl *gomock.Controller) *MockCursor {
	mock := &MockCursor{ctrl: ctrl}
	mock.recorder = &MockCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursor) EXPECT() *MockCursorMockRecorder {
	return m.recorder
}

// GetOffset mocks base method.
func (m *MockCursor) GetOffset() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOffset")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetOffset indicates an expected call of GetOffset.
func (mr *MockCursorMockRecorder) GetOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOffset", reflect.TypeOf((*MockCursor)(nil).GetOffset))
}

// MarshalBinary mocks base method.
func (m *MockCursor) MarshalBinary() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalBinary")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalBinary indicates an expected call of MarshalBinary.
func (mr *MockCursorMockRecorder) MarshalBinary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalBinary", reflect.TypeOf((*MockCursor)(nil).MarshalBinary))
}

// Query mocks base method.
func (m *MockCursor) Query(table string) func(*gorm.DB) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", table)
	ret0, _ := ret[0].(func(*gorm.DB) *gorm.DB)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockCursorMockRecorder) Query(table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockCursor)(nil).Query), table)
}

// UnmarshalBinary mocks base method.
func (m *MockCursor) UnmarshalBinary(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalBinary", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalBinary indicates an expected call of UnmarshalBinary.
func (mr *MockCursorMockRecorder) UnmarshalBinary(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalBinary", reflect.TypeOf((*MockCursor)(nil).UnmarshalBinary), data)
}
