// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: DatabaseConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/database_config.go -package=test -mock_names=DatabaseConfigger=MockDatabaseConfig . DatabaseConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseConfig is a mock of DatabaseConfigger interface.
type MockDatabaseConfig struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseConfigMockRecorder
	isgomock struct{}
}

// MockDatabaseConfigMockRecorder is the mock recorder for MockDatabaseConfig.
type MockDatabaseConfigMockRecorder struct {
	mock *MockDatabaseConfig
}

// NewMockDatabaseConfig creates a new mock instance.
func NewMockDatabaseConfig(ctrl *gomock.Controller) *MockDatabaseConfig {
	mock := &MockDatabaseConfig{ctrl: ctrl}
	mock.recorder = &MockDatabaseConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseConfig) EXPECT() *MockDatabaseConfigMockRecorder {
	return m.recorder
}

// GetDSN mocks base method.
func (m *MockDatabaseConfig) GetDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDSN indicates an expected call of GetDSN.
func (mr *MockDatabaseConfigMockRecorder) GetDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDSN", reflect.TypeOf((*MockDatabaseConfig)(nil).GetDSN))
}
