// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: EndpointConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/endpoint_config.go -package=test -mock_names=EndpointConfigger=MockEndpointConfig . EndpointConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEndpointConfig is a mock of EndpointConfigger interface.
type MockEndpointConfig struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointConfigMockRecorder
	isgomock struct{}
}

// MockEndpointConfigMockRecorder is the mock recorder for MockEndpointConfig.
type MockEndpointConfigMockRecorder struct {
	mock *MockEndpointConfig
}

// NewMockEndpointConfig creates a new mock instance.
func NewMockEndpointConfig(ctrl *gomock.Controller) *MockEndpointConfig {
	mock := &MockEndpointConfig{ctrl: ctrl}
	mock.recorder = &MockEndpointConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointConfig) EXPECT() *MockEndpointConfigMockRecorder {
	return m.recorder
}

// GetAddr mocks base method.
func (m *MockEndpointConfig) GetAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAddr indicates an expected call of GetAddr.
func (mr *MockEndpointConfigMockRecorder) GetAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddr", reflect.TypeOf((*MockEndpointConfig)(nil).GetAddr))
}

// GetNetwork mocks base method.
func (m *MockEndpointConfig) GetNetwork() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockEndpointConfigMockRecorder) GetNetwork() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockEndpointConfig)(nil).GetNetwork))
}
