// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/object/dao (interfaces: Filterer)
//
// Generated by this command:
//
//	mockgen -destination=../../test/v2/filter.go -package=test -mock_names=Filterer=MockFilter . Filterer
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockFilter is a mock of Filterer interface.
type MockFilter struct {
	ctrl     *gomock.Controller
	recorder *MockFilterMockRecorder
	isgomock struct{}
}

// MockFilterMockRecorder is the mock recorder for MockFilter.
type MockFilterMockRecorder struct {
	mock *MockFilter
}

// NewMockFilter creates a new mock instance.
func NewMockFilter(ctrl *gomock.Controller) *MockFilter {
	mock := &MockFilter{ctrl: ctrl}
	mock.recorder = &MockFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilter) EXPECT() *MockFilterMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockFilter) Filter(arg0 *gorm.DB) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", arg0)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockFilterMockRecorder) Filter(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockFilter)(nil).Filter), arg0)
}
