// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: HTTPConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/http_config.go -package=test -mock_names=HTTPConfigger=MockHTTPConfig . HTTPConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPConfig is a mock of HTTPConfigger interface.
type MockHTTPConfig struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPConfigMockRecorder
	isgomock struct{}
}

// MockHTTPConfigMockRecorder is the mock recorder for MockHTTPConfig.
type MockHTTPConfigMockRecorder struct {
	mock *MockHTTPConfig
}

// NewMockHTTPConfig creates a new mock instance.
func NewMockHTTPConfig(ctrl *gomock.Controller) *MockHTTPConfig {
	mock := &MockHTTPConfig{ctrl: ctrl}
	mock.recorder = &MockHTTPConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPConfig) EXPECT() *MockHTTPConfigMockRecorder {
	return m.recorder
}

// GetAddr mocks base method.
func (m *MockHTTPConfig) GetAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAddr indicates an expected call of GetAddr.
func (mr *MockHTTPConfigMockRecorder) GetAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddr", reflect.TypeOf((*MockHTTPConfig)(nil).GetAddr))
}
