// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: LogConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/log_config.go -package=test -mock_names=LogConfigger=MockLogConfig . LogConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLogConfig is a mock of LogConfigger interface.
type MockLogConfig struct {
	ctrl     *gomock.Controller
	recorder *MockLogConfigMockRecorder
	isgomock struct{}
}

// MockLogConfigMockRecorder is the mock recorder for MockLogConfig.
type MockLogConfigMockRecorder struct {
	mock *MockLogConfig
}

// NewMockLogConfig creates a new mock instance.
func NewMockLogConfig(ctrl *gomock.Controller) *MockLogConfig {
	mock := &MockLogConfig{ctrl: ctrl}
	mock.recorder = &MockLogConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogConfig) EXPECT() *MockLogConfigMockRecorder {
	return m.recorder
}

// GetCompress mocks base method.
func (m *MockLogConfig) GetCompress() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompress")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetCompress indicates an expected call of GetCompress.
func (mr *MockLogConfigMockRecorder) GetCompress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompress", reflect.TypeOf((*MockLogConfig)(nil).GetCompress))
}

// GetFile mocks base method.
func (m *MockLogConfig) GetFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFile indicates an expected call of GetFile.
func (mr *MockLogConfigMockRecorder) GetFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockLogConfig)(nil).GetFile))
}

// GetFormat mocks base method.
func (m *MockLogConfig) GetFormat() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormat")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFormat indicates an expected call of GetFormat.
func (mr *MockLogConfigMockRecorder) GetFormat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormat", reflect.TypeOf((*MockLogConfig)(nil).GetFormat))
}

// GetLevel mocks base method.
func (m *MockLogConfig) GetLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLevel indicates an expected call of GetLevel.
func (mr *MockLogConfigMockRecorder) GetLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLevel", reflect.TypeOf((*MockLogConfig)(nil).GetLevel))
}

// GetLocalTime mocks base method.
func (m *MockLogConfig) GetLocalTime() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalTime")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetLocalTime indicates an expected call of GetLocalTime.
func (mr *MockLogConfigMockRecorder) GetLocalTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalTime", reflect.TypeOf((*MockLogConfig)(nil).GetLocalTime))
}

// GetMaxAge mocks base method.
func (m *MockLogConfig) GetMaxAge() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxAge")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxAge indicates an expected call of GetMaxAge.
func (mr *MockLogConfigMockRecorder) GetMaxAge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxAge", reflect.TypeOf((*MockLogConfig)(nil).GetMaxAge))
}

// GetMaxBackups mocks base method.
func (m *MockLogConfig) GetMaxBackups() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxBackups")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxBackups indicates an expected call of GetMaxBackups.
func (mr *MockLogConfigMockRecorder) GetMaxBackups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxBackups", reflect.TypeOf((*MockLogConfig)(nil).GetMaxBackups))
}

// GetMaxSize mocks base method.
func (m *MockLogConfig) GetMaxSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxSize indicates an expected call of GetMaxSize.
func (mr *MockLogConfigMockRecorder) GetMaxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxSize", reflect.TypeOf((*MockLogConfig)(nil).GetMaxSize))
}

// GetRotation mocks base method.
func (m *MockLogConfig) GetRotation() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRotation")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetRotation indicates an expected call of GetRotation.
func (mr *MockLogConfigMockRecorder) GetRotation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRotation", reflect.TypeOf((*MockLogConfig)(nil).GetRotation))
}

// GetSQLSlowThreshold mocks base method.
func (m *MockLogConfig) GetSQLSlowThreshold() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSQLSlowThreshold")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetSQLSlowThreshold indicates an expected call of GetSQLSlowThreshold.
func (mr *MockLogConfigMockRecorder) GetSQLSlowThreshold() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSQLSlowThreshold", reflect.TypeOf((*MockLogConfig)(nil).GetSQLSlowThreshold))
}

// GetStdout mocks base method.
func (m *MockLogConfig) GetStdout() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStdout")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetStdout indicates an expected call of GetStdout.
func (mr *MockLogConfigMockRecorder) GetStdout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStdout", reflect.TypeOf((*MockLogConfig)(nil).GetStdout))
}
