// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: OtelConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/otel_config.go -package=test -mock_names=OtelConfigger=MockOtelConfig . OtelConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOtelConfig is a mock of OtelConfigger interface.
type MockOtelConfig struct {
	ctrl     *gomock.Controller
	recorder *MockOtelConfigMockRecorder
	isgomock struct{}
}

// MockOtelConfigMockRecorder is the mock recorder for MockOtelConfig.
type MockOtelConfigMockRecorder struct {
	mock *MockOtelConfig
}

// NewMockOtelConfig creates a new mock instance.
func NewMockOtelConfig(ctrl *gomock.Controller) *MockOtelConfig {
	mock := &MockOtelConfig{ctrl: ctrl}
	mock.recorder = &MockOtelConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOtelConfig) EXPECT() *MockOtelConfigMockRecorder {
	return m.recorder
}

// GetExporterOTLPTracesEndpoint mocks base method.
func (m *MockOtelConfig) GetExporterOTLPTracesEndpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExporterOTLPTracesEndpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExporterOTLPTracesEndpoint indicates an expected call of GetExporterOTLPTracesEndpoint.
func (mr *MockOtelConfigMockRecorder) GetExporterOTLPTracesEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExporterOTLPTracesEndpoint", reflect.TypeOf((*MockOtelConfig)(nil).GetExporterOTLPTracesEndpoint))
}

// GetInstrumentationName mocks base method.
func (m *MockOtelConfig) GetInstrumentationName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstrumentationName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInstrumentationName indicates an expected call of GetInstrumentationName.
func (mr *MockOtelConfigMockRecorder) GetInstrumentationName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstrumentationName", reflect.TypeOf((*MockOtelConfig)(nil).GetInstrumentationName))
}

// GetServiceInstanceID mocks base method.
func (m *MockOtelConfig) GetServiceInstanceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInstanceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceInstanceID indicates an expected call of GetServiceInstanceID.
func (mr *MockOtelConfigMockRecorder) GetServiceInstanceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInstanceID", reflect.TypeOf((*MockOtelConfig)(nil).GetServiceInstanceID))
}

// GetServiceName mocks base method.
func (m *MockOtelConfig) GetServiceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceName indicates an expected call of GetServiceName.
func (mr *MockOtelConfigMockRecorder) GetServiceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceName", reflect.TypeOf((*MockOtelConfig)(nil).GetServiceName))
}

// GetServiceNamespace mocks base method.
func (m *MockOtelConfig) GetServiceNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceNamespace indicates an expected call of GetServiceNamespace.
func (mr *MockOtelConfigMockRecorder) GetServiceNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceNamespace", reflect.TypeOf((*MockOtelConfig)(nil).GetServiceNamespace))
}

// GetServiceVersion mocks base method.
func (m *MockOtelConfig) GetServiceVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceVersion indicates an expected call of GetServiceVersion.
func (mr *MockOtelConfigMockRecorder) GetServiceVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceVersion", reflect.TypeOf((*MockOtelConfig)(nil).GetServiceVersion))
}
