// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/object/dao (interfaces: Paginationer)
//
// Generated by this command:
//
//	mockgen -destination=../../test/v2/pagination.go -package=test -mock_names=Paginationer=MockPagination . Paginationer
//

// Package test is a generated GoMock package.
package test

import (
	dao "github/M2A96/Monopoly.git/object/dao"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPagination is a mock of Paginationer interface.
type MockPagination struct {
	ctrl     *gomock.Controller
	recorder *MockPaginationMockRecorder
	isgomock struct{}
}

// MockPaginationMockRecorder is the mock recorder for MockPagination.
type MockPaginationMockRecorder struct {
	mock *MockPagination
}

// NewMockPagination creates a new mock instance.
func NewMockPagination(ctrl *gomock.Controller) *MockPagination {
	mock := &MockPagination{ctrl: ctrl}
	mock.recorder = &MockPaginationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPagination) EXPECT() *MockPaginationMockRecorder {
	return m.recorder
}

// GetCursorer mocks base method.
func (m *MockPagination) GetCursorer() dao.Cursorer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursorer")
	ret0, _ := ret[0].(dao.Cursorer)
	return ret0
}

// GetCursorer indicates an expected call of GetCursorer.
func (mr *MockPaginationMockRecorder) GetCursorer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursorer", reflect.TypeOf((*MockPagination)(nil).GetCursorer))
}

// GetLimit mocks base method.
func (m *MockPagination) GetLimit() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimit")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetLimit indicates an expected call of GetLimit.
func (mr *MockPaginationMockRecorder) GetLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimit", reflect.TypeOf((*MockPagination)(nil).GetLimit))
}

// Pagination mocks base method.
func (m *MockPagination) Pagination(table string) func(*gorm.DB) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pagination", table)
	ret0, _ := ret[0].(func(*gorm.DB) *gorm.DB)
	return ret0
}

// Pagination indicates an expected call of Pagination.
func (mr *MockPaginationMockRecorder) Pagination(table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pagination", reflect.TypeOf((*MockPagination)(nil).Pagination), table)
}
