// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: RuntimeConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/runtime_config.go -package=test -mock_names=RuntimeConfigger=MockRuntimeConfig . RuntimeConfigger
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRuntimeConfig is a mock of RuntimeConfigger interface.
type MockRuntimeConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeConfigMockRecorder
	isgomock struct{}
}

// MockRuntimeConfigMockRecorder is the mock recorder for MockRuntimeConfig.
type MockRuntimeConfigMockRecorder struct {
	mock *MockRuntimeConfig
}

// NewMockRuntimeConfig creates a new mock instance.
func NewMockRuntimeConfig(ctrl *gomock.Controller) *MockRuntimeConfig {
	mock := &MockRuntimeConfig{ctrl: ctrl}
	mock.recorder = &MockRuntimeConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeConfig) EXPECT() *MockRuntimeConfigMockRecorder {
	return m.recorder
}

// GetClientPaginationRequestSizeMax mocks base method.
func (m *MockRuntimeConfig) GetClientPaginationRequestSizeMax() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientPaginationRequestSizeMax")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetClientPaginationRequestSizeMax indicates an expected call of GetClientPaginationRequestSizeMax.
func (mr *MockRuntimeConfigMockRecorder) GetClientPaginationRequestSizeMax() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientPaginationRequestSizeMax", reflect.TypeOf((*MockRuntimeConfig)(nil).GetClientPaginationRequestSizeMax))
}

// GetValidateMapRules mocks base method.
func (m *MockRuntimeConfig) GetValidateMapRules() map[string][]map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidateMapRules")
	ret0, _ := ret[0].(map[string][]map[string]any)
	return ret0
}

// GetValidateMapRules indicates an expected call of GetValidateMapRules.
func (mr *MockRuntimeConfigMockRecorder) GetValidateMapRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidateMapRules", reflect.TypeOf((*MockRuntimeConfig)(nil).GetValidateMapRules))
}
