// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/log (interfaces: RuntimeLogger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/runtime_log.go -package=test -mock_names=RuntimeLogger=MockRuntimeLog . RuntimeLogger
//

// Package test is a generated GoMock package.
package test

import (
	log "github/M2A96/Monopoly.git/log"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRuntimeLog is a mock of RuntimeLogger interface.
type MockRuntimeLog struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeLogMockRecorder
	isgomock struct{}
}

// MockRuntimeLogMockRecorder is the mock recorder for MockRuntimeLog.
type MockRuntimeLogMockRecorder struct {
	mock *MockRuntimeLog
}

// NewMockRuntimeLog creates a new mock instance.
func NewMockRuntimeLog(ctrl *gomock.Controller) *MockRuntimeLog {
	mock := &MockRuntimeLog{ctrl: ctrl}
	mock.recorder = &MockRuntimeLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeLog) EXPECT() *MockRuntimeLogMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockRuntimeLog) Debug(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockRuntimeLogMockRecorder) Debug(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockRuntimeLog)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockRuntimeLog) Error(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockRuntimeLogMockRecorder) Error(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockRuntimeLog)(nil).Error), varargs...)
}

// Fatal mocks base method.
func (m *MockRuntimeLog) Fatal(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockRuntimeLogMockRecorder) Fatal(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockRuntimeLog)(nil).Fatal), varargs...)
}

// Fields mocks base method.
func (m *MockRuntimeLog) Fields() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fields")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Fields indicates an expected call of Fields.
func (mr *MockRuntimeLogMockRecorder) Fields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fields", reflect.TypeOf((*MockRuntimeLog)(nil).Fields))
}

// Info mocks base method.
func (m *MockRuntimeLog) Info(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockRuntimeLogMockRecorder) Info(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockRuntimeLog)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockRuntimeLog) Warn(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockRuntimeLogMockRecorder) Warn(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockRuntimeLog)(nil).Warn), varargs...)
}

// WithField mocks base method.
func (m *MockRuntimeLog) WithField(arg0 string, arg1 any) log.RuntimeLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithField", arg0, arg1)
	ret0, _ := ret[0].(log.RuntimeLogger)
	return ret0
}

// WithField indicates an expected call of WithField.
func (mr *MockRuntimeLogMockRecorder) WithField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithField", reflect.TypeOf((*MockRuntimeLog)(nil).WithField), arg0, arg1)
}

// WithFields mocks base method.
func (m *MockRuntimeLog) WithFields(arg0 map[string]any) log.RuntimeLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFields", arg0)
	ret0, _ := ret[0].(log.RuntimeLogger)
	return ret0
}

// WithFields indicates an expected call of WithFields.
func (mr *MockRuntimeLogMockRecorder) WithFields(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFields", reflect.TypeOf((*MockRuntimeLog)(nil).WithFields), arg0)
}
