// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/config (interfaces: ServerConfigger)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/server_config.go -package=test -mock_names=ServerConfigger=MockServerConfig . ServerConfigger
//

// Package test is a generated GoMock package.
package test

import (
	config "github/M2A96/Monopoly.git/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServerConfig is a mock of ServerConfigger interface.
type MockServerConfig struct {
	ctrl     *gomock.Controller
	recorder *MockServerConfigMockRecorder
	isgomock struct{}
}

// MockServerConfigMockRecorder is the mock recorder for MockServerConfig.
type MockServerConfigMockRecorder struct {
	mock *MockServerConfig
}

// NewMockServerConfig creates a new mock instance.
func NewMockServerConfig(ctrl *gomock.Controller) *MockServerConfig {
	mock := &MockServerConfig{ctrl: ctrl}
	mock.recorder = &MockServerConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerConfig) EXPECT() *MockServerConfigMockRecorder {
	return m.recorder
}

// GetEndpointConfigger mocks base method.
func (m *MockServerConfig) GetEndpointConfigger() config.EndpointConfigger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndpointConfigger")
	ret0, _ := ret[0].(config.EndpointConfigger)
	return ret0
}

// GetEndpointConfigger indicates an expected call of GetEndpointConfigger.
func (mr *MockServerConfigMockRecorder) GetEndpointConfigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndpointConfigger", reflect.TypeOf((*MockServerConfig)(nil).GetEndpointConfigger))
}
