// Code generated by MockGen. DO NOT EDIT.
// Source: github/M2A96/Monopoly.git/object (interfaces: Timer)
//
// Generated by this command:
//
//	mockgen -destination=../test/v2/time.go -package=test -mock_names=Timer=MockTime . Timer
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTime is a mock of Timer interface.
type MockTime struct {
	ctrl     *gomock.Controller
	recorder *MockTimeMockRecorder
	isgomock struct{}
}

// MockTimeMockRecorder is the mock recorder for MockTime.
type MockTimeMockRecorder struct {
	mock *MockTime
}

// NewMockTime creates a new mock instance.
func NewMockTime(ctrl *gomock.Controller) *MockTime {
	mock := &MockTime{ctrl: ctrl}
	mock.recorder = &MockTimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTime) EXPECT() *MockTimeMockRecorder {
	return m.recorder
}

// NowUTC mocks base method.
func (m *MockTime) NowUTC() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NowUTC")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// NowUTC indicates an expected call of NowUTC.
func (mr *MockTimeMockRecorder) NowUTC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NowUTC", reflect.TypeOf((*MockTime)(nil).NowUTC))
}

// Since mocks base method.
func (m *MockTime) Since(arg0 time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", arg0)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since.
func (mr *MockTimeMockRecorder) Since(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockTime)(nil).Since), arg0)
}
