DROP TABLE IF EXISTS GAME;

DROP TABLE IF EXISTS PLAYER; 

DROP TABLE IF EXISTS PROPERTY; 

DROP TABLE IF EXISTS PLAYER_PROPERTY ;

DROP TABLE IF EXISTS BOARD_SPACE ;

DROP TABLE IF EXISTS CARD ;

DROP TABLE IF EXISTS GAME_LOG ;

DROP TABLE IF EXISTS GAME_HOUSE_HOTEL_BANK;
